---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# Doc: https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2
nodes:
################################################################################
# Control Plane
################################################################################
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      name: "k8s-control-plane"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
################################################################################
# Workers
################################################################################
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: "k8s-wrk-001"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: "k8s-wrk-002"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: "k8s-wrk-003"
################################################################################
# Network
################################################################################
networking:
  disableDefaultCNI: true
  podSubnet: 10.27.0.0/16
  serviceSubnet: 172.27.0.0/24
